//Sujith Sasikumar//

CREATE TABLE STUDENT_GRADE(
Roll_no INT,
Name VARCHAR(30),
M1 FLOAT,
M2 FLOAT,
M3 FLOAT,
M4 FLOAT,
M5 FLOAT,
M6 FLOAT
);

INSERT INTO STUDENT_GRADE
VALUES(10, 'CHANDLER', 80, 90, 67, 88, 79, 98),
(11, 'MONICA', 80, 85, 72, 81, 59, 58),
(12, 'JOEY', 60, 51, 46, 51, 59, 58);

DELIMITER $
DROP PROCEDURE IF EXISTS stud_grade;

CREATE PROCEDURE stud_grade()

BEGIN
  DECLARE TOTAL_MARK FLOAT DEFAULT 0;
  DECLARE n1,n2,n3,n4,n5,n6 FLOAT;
  DECLARE FIN INT DEFAULT 0;
  DECLARE G CHAR(5);

  DECLARE CUR CURSOR FOR SELECT M1,M2,M3,M4,M5,M6 FROM STUDENT_GRADE
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIN=1;
  
  OPEN CUR;
  count_total: LOOP
    FETCH CUR INTO n1,n2,n3,n4,n5,n6;

    IF FIN=1 THEN 
      LEAVE count_total;
    END IF;
    
    SET TOTAL_MARK = n1+n2+n3+n4+n5+n6;

CREATE TABLE disp(Grade_of_student CHAR(5), Mark_Total FLOAT);
 IF TOTAL_MARK>480 THEN
  SET G="A";
 ELSEIF TOTAL_MARK>400 THEN
  SET G="B+";
 ELSEIF TOTAL_MARK>360 THEN
  SET G="B";
 ELSEIF TOTAL_MARK>300 THEN
  SET G="C";
 ELSE
  SET G="F";
 END IF;

INSERT INTO disp values(G,TOTAL_MARK);
SELECT*FROM disp;
DROP TABLE disp;
 END LOOP count_total;
CLOSE CUR;

END $


CALL stud_grade();















